@startuml
class CharacterMovement {
 - playerSprite : GameObject
 - rigidbody2d : Rigidbody2D
 - animator : Animator
 - horizontalAxis : float
 - verticalAxis : float
 - facingRight : bool
 - grounded : bool
 + groundCheck : Collider2D
 + groundMask : LayerMask
 + speed : float
 - climbing : bool
 + onLadder : bool
 - prevGravity : float
 + jumpForce : float
 - jumpPressed : bool
 - jumping : bool
 + lives : int
 + score : int
 + time : int
 void Awake()
 void Update()
 void FixedUpdate()
 void CheckGrounded()
 void RunHandler()
 void JumpHandler()
 void LadderHandler()
 void Flip()
 void Jump()
 void BeginClimbing()
 void StopClimbing()
}

class Crocodile {
 + mouthOpen : bool
}

class Barrel {
 - speed : int
}

class VineController {
 + amplitude : float
 + period : float
 - elapsedTime : float
}
@enduml
